version: "2.4"

volumes:
  db:

services:
  app:
    build: .
    env_file:
      - .env
    # command: >
    #   sh -c "cd assets && npm rebuild node-sass && cd .. && mix phx.server"
    volumes:
      - ./src:/home/app/phoenix
    expose:
      - 4000
    ports:
      - 4000:4000
    depends_on:
      - db

  db:
    image: mariadb:latest
    env_file:
      - .env
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - db:/var/lib/mysql
