version: "2.4"

volumes:
  db:

networks:
  {{ app }}-default:
    driver: bridge

services:
  app:
    build: .
    container_name: "{{ app }}-app"
    env_file:
      - .env
    # command: >
    #   sh -c "cd assets && npm rebuild node-sass && cd .. && mix phx.server"
    volumes:
      - ./src:/home/app/phoenix
    expose:
      - 4000
    ports:
      - 4000:4000
    depends_on:
      - db
    networks:
      - {{ app }}-default

  db:
    image: mariadb:11.1.3
    container_name: "{{ app }}-db"
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - {{ app }}-default
